### ISSUE TITLE
no images in mobile version

### ISSUE THREAD

**Issue by gonzzza007** [artweb-ou/trickster-cms#2]
Hi! I am experiencing a strange issue. I don't see any images on website when opening on older phones. For example IphoneSE, android phones.
Completely disabling the CSS didn't help - so the problem is in image loading not styling issue.

I have latest GitHub version installed. No image related errors in error log, only missing translations.
How can I debug the issue? Should I provide more data?
The website is https://moonavoor.ee/

**Comment by ghost** [comment]
CMS uses webp format for all the outgoing generated images. It detects browser support by http headers checking and if webp is unsupported, uses jpg/png instead.
I would start from debugging the images generation and format detection.

**Comment by gonzzza007** [comment]
I think you're right. It has something to do with 'lazy_image'. Don't know what it is as I couldn't find any documentation :)
But I love the way this CMS is written and starting to understand how it works.

Thank you!

**Comment by ghost** [comment]
Actually I seem to know the answer. This has to be related to Intersection Observer API unsupported in Safari.
The fix will go to ver/3 branch.

**Comment by gonzzza007** [comment]
Wow, that's great! I will be keeping an eye on ver/3 branch then. Thanks a lot!

**Comment by ghost** [comment]
Fixed in 3.9.20
